language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -U pip
  - pip install -r requirements/devel.txt
  - python -m spacy download en_core_web_sm
# command to run tests
script:
  - python -m pytest -v
