language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pip
    - $HOME/linker_smxm
    - $HOME/blink_linker
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -U pip
  - pip install -r requirements/devel.txt
  - python -m spacy download en_core_web_sm
  # Install the mkdocs dependencies
  - pip install mkdocs mkdocs-material mkdocstrings[python] mkdocs-markdownextradata-plugin mdx_include

# command to run tests
script:
  - flake8 --ignore E501 zshot/
  - python -m pytest -v

before_deploy:
    - mkdocs build --verbose --clean --strict

deploy: # Deploy documentation to Github in the gh_pages branch
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: site
    github_url: github.ibm.com
    on:
        branch: master
